class MsgCore:

    def __init__(self):
        self.StartGetToken = "开始获取Token"
        self.GetTokenSuccess = "获取Token成功"
        self.StartGetData = "开始获取数据"
        self.GetDataSuccess = "获取数据成功"
        self.StartWriteData = "开始写入数据"
        self.WriteDataSuccess = "写入数据成功!"
        self.NoNetWorkConnection = "没有网络连接,请重试"
        self.ContinueOrQuit = "按任意键继续或按Q退出"
        self.UnsupportedDB = "不支持此类型数据库"
        self.WrongDataFormat = "API返回的数据格式错误,请重试"
        self.UnknowProfileID = "未知的配置项,请重试."
        self.SelectProfile = "请选择一项配置进行数据下载与分析"
        self.SelectProfileUpline = "=[ID]=[Profile]==========="
        self.SelectProfileDownline = "=========================="
        self.CopyFileToRawData = "复制文件到RawData文件夹"
        self.CallMergeBat = "调用Merge.bat"
        self.CopyFileToData = "复制文件到Data文件夹"
        self.CallStartBat = "调用Start.bat"
        self.OpenDataFolder = "打开Data文件夹"
        self.FailedGetAccentToken = "获取AccentToken失败请重试"
        self.ContinueOrQuitForRetryFunction = "已尝试10次,是否需要继续重试10次?"
        self.TimeCountOfRetry = "正在重试第<<%s>>次"
        self.UnknowSelection = "UnknowSelection"
